# Development Dockerfile for Client
FROM node:16.20.2-buster-slim

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose port 8080 for the client
EXPOSE 8080

# Default command for development (with hot reload)
CMD ["npm", "start"]
