services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    container_name: client-dev
    ports:
      - '8080:8080'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    container_name: server-dev
    environment:
      - PORT=3000
      - NODE_ENV=development
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=insalijdaihfanfdadaihfoalkdmfoieboandslfiebalenfdainfasdc
      - MONGO_URI=mongodb://host.docker.internal:27017/market-hub
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: [
        'sh',
        '-c',
        'npm run seed:db dhruvmes.8555@gmail.com admin123 && npm run dev'
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
