version: '3.8'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - API_URL=http://13.235.73.151:3001/api
    container_name: market-hub-client
    ports:
      - '80:8080'
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: market-hub-server
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost
      - JWT_SECRET=insalijdaihfanfdadaihfoalkdmfoieboandslfiebalenfdainfasdc
      - MONGO_URI=mongodb://mongo:27017/market_hub
      - MAILGUN_KEY=your_mailgun_key_here
      - MAILGUN_DOMAIN=your_mailgun_domain_here
      - MAILGUN_EMAIL_SENDER=your_mailgun_sender_here
      - MAILCHIMP_KEY=your_mailchimp_key_here
      - MAILCHIMP_LIST_KEY=your_mailchimp_list_key_here
      - GOOGLE_CLIENT_ID=your_google_client_id_here
      - GOOGLE_CLIENT_SECRET=your_google_client_secret_here
      - GOOGLE_CALLBACK_URL=http://localhost:3000/api/auth/google/callback
      - FACEBOOK_CLIENT_ID=your_facebook_client_id_here
      - FACEBOOK_CLIENT_SECRET=your_facebook_client_secret_here
      - FACEBOOK_CALLBACK_URL=http://localhost:3000/api/auth/facebook/callback
      - AWS_ACCESS_KEY_ID=your_aws_access_key_here
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key_here
      - AWS_REGION=us-east-1
      - AWS_BUCKET_NAME=your_s3_bucket_name_here
    depends_on:
      - mongo
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 10 &&
        echo 'Seeding database...' &&
        npm run seed:db admin@market-hub.com admin123 &&
        echo 'Starting server...' &&
        npm start
      "

  mongo:
    image: mongo:latest
    container_name: market-hub-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
